baseurl = "/"
languageCode = "hu"
languageLang = "hu"
title = "Szemes Ágnes"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
